/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ForInstitutesRouteImport } from './routes/for-institutes'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdmissionsRouteImport } from './routes/app.admissions'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppBatchesRouteImport } from './routes/app.batches'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppFacultyRouteImport } from './routes/app.faculty'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppGroupRouteImport } from './routes/app.group'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppPlatformRouteImport } from './routes/app.platform'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSalariesRouteImport } from './routes/app.salaries'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSyllabusRouteImport } from './routes/app.syllabus'
import { Route as AppTestsRouteImport } from './routes/app.tests'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as OnboardTokenRouteImport } from './routes/onboard.$token'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAttendanceRouteImport } from './routes/portal.attendance'
import { Route as PortalFeesRouteImport } from './routes/portal.fees'
import { Route as PortalHomeworkRouteImport } from './routes/portal.homework'
import { Route as PortalProgressRouteImport } from './routes/portal.progress'
import { Route as PortalTimetableRouteImport } from './routes/portal.timetable'
import { Route as TeachIndexRouteImport } from './routes/teach.index'
import { Route as TeachAttendanceRouteImport } from './routes/teach.attendance'
import { Route as TeachMarksRouteImport } from './routes/teach.marks'
import { Route as TeachSyllabusRouteImport } from './routes/teach.syllabus'
import { Route as WelcomeTokenRouteImport } from './routes/welcome.$token'
import { Route as AppBatchesIdRouteImport } from './routes/app.batches.$id'
import { Route as AppPlatformIndexRouteImport } from './routes/app.platform.index'
import { Route as AppPlatformFeaturesRouteImport } from './routes/app.platform.features'
import { Route as AppPlatformInstitutesRouteImport } from './routes/app.platform.institutes'
import { Route as AppPlatformPlansRouteImport } from './routes/app.platform.plans'
import { Route as AppStudentsIdRouteImport } from './routes/app.students.$id'
import { Route as AppTestsIdRouteImport } from './routes/app.tests.$id'
import { Route as ApiPublicAttendancePunchRouteImport } from './routes/api/public/attendance.punch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ForInstitutesRoute = ForInstitutesRouteImport.update({
  id: '/for-institutes',
  path: '/for-institutes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesRoute = AppBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupRoute = AppGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalariesRoute = AppSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSyllabusRoute = AppSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTokenRoute = OnboardTokenRouteImport.update({
  id: '/onboard/$token',
  path: '/onboard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAttendanceRoute = PortalAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFeesRoute = PortalFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHomeworkRoute = PortalHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProgressRoute = PortalProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTimetableRoute = PortalTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => PortalRoute,
} as any)
const TeachIndexRoute = TeachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachRoute,
} as any)
const TeachAttendanceRoute = TeachAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeachRoute,
} as any)
const TeachMarksRoute = TeachMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => TeachRoute,
} as any)
const TeachSyllabusRoute = TeachSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => TeachRoute,
} as any)
const WelcomeTokenRoute = WelcomeTokenRouteImport.update({
  id: '/welcome/$token',
  path: '/welcome/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBatchesIdRoute = AppBatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBatchesRoute,
} as any)
const AppPlatformIndexRoute = AppPlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformFeaturesRoute = AppPlatformFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformInstitutesRoute = AppPlatformInstitutesRouteImport.update({
  id: '/institutes',
  path: '/institutes',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformPlansRoute = AppPlatformPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentsRoute,
} as any)
const AppTestsIdRoute = AppTestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTestsRoute,
} as any)
const ApiPublicAttendancePunchRoute =
  ApiPublicAttendancePunchRouteImport.update({
    id: '/api/public/attendance/punch',
    path: '/api/public/attendance/punch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/apply': typeof ApplyRoute
  '/for-institutes': typeof ForInstitutesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/pending': typeof PendingRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/teach': typeof TeachRouteWithChildren
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/batches': typeof AppBatchesRouteWithChildren
  '/app/expenses': typeof AppExpensesRoute
  '/app/faculty': typeof AppFacultyRoute
  '/app/fees': typeof AppFeesRoute
  '/app/group': typeof AppGroupRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/platform': typeof AppPlatformRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/salaries': typeof AppSalariesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/syllabus': typeof AppSyllabusRoute
  '/app/tests': typeof AppTestsRouteWithChildren
  '/app/timetable': typeof AppTimetableRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/login/$': typeof LoginSplatRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/portal/attendance': typeof PortalAttendanceRoute
  '/portal/fees': typeof PortalFeesRoute
  '/portal/homework': typeof PortalHomeworkRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/timetable': typeof PortalTimetableRoute
  '/teach/attendance': typeof TeachAttendanceRoute
  '/teach/marks': typeof TeachMarksRoute
  '/teach/syllabus': typeof TeachSyllabusRoute
  '/welcome/$token': typeof WelcomeTokenRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/teach/': typeof TeachIndexRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/platform/features': typeof AppPlatformFeaturesRoute
  '/app/platform/institutes': typeof AppPlatformInstitutesRoute
  '/app/platform/plans': typeof AppPlatformPlansRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/tests/$id': typeof AppTestsIdRoute
  '/app/platform/': typeof AppPlatformIndexRoute
  '/api/public/attendance/punch': typeof ApiPublicAttendancePunchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/for-institutes': typeof ForInstitutesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/pending': typeof PendingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/batches': typeof AppBatchesRouteWithChildren
  '/app/expenses': typeof AppExpensesRoute
  '/app/faculty': typeof AppFacultyRoute
  '/app/fees': typeof AppFeesRoute
  '/app/group': typeof AppGroupRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/salaries': typeof AppSalariesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/syllabus': typeof AppSyllabusRoute
  '/app/tests': typeof AppTestsRouteWithChildren
  '/app/timetable': typeof AppTimetableRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/login/$': typeof LoginSplatRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/portal/attendance': typeof PortalAttendanceRoute
  '/portal/fees': typeof PortalFeesRoute
  '/portal/homework': typeof PortalHomeworkRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/timetable': typeof PortalTimetableRoute
  '/teach/attendance': typeof TeachAttendanceRoute
  '/teach/marks': typeof TeachMarksRoute
  '/teach/syllabus': typeof TeachSyllabusRoute
  '/welcome/$token': typeof WelcomeTokenRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/portal': typeof PortalIndexRoute
  '/teach': typeof TeachIndexRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/platform/features': typeof AppPlatformFeaturesRoute
  '/app/platform/institutes': typeof AppPlatformInstitutesRoute
  '/app/platform/plans': typeof AppPlatformPlansRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/tests/$id': typeof AppTestsIdRoute
  '/app/platform': typeof AppPlatformIndexRoute
  '/api/public/attendance/punch': typeof ApiPublicAttendancePunchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/apply': typeof ApplyRoute
  '/for-institutes': typeof ForInstitutesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/pending': typeof PendingRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/teach': typeof TeachRouteWithChildren
  '/app/admissions': typeof AppAdmissionsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/batches': typeof AppBatchesRouteWithChildren
  '/app/expenses': typeof AppExpensesRoute
  '/app/faculty': typeof AppFacultyRoute
  '/app/fees': typeof AppFeesRoute
  '/app/group': typeof AppGroupRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/platform': typeof AppPlatformRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/salaries': typeof AppSalariesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/syllabus': typeof AppSyllabusRoute
  '/app/tests': typeof AppTestsRouteWithChildren
  '/app/timetable': typeof AppTimetableRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/login/$': typeof LoginSplatRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/portal/attendance': typeof PortalAttendanceRoute
  '/portal/fees': typeof PortalFeesRoute
  '/portal/homework': typeof PortalHomeworkRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/timetable': typeof PortalTimetableRoute
  '/teach/attendance': typeof TeachAttendanceRoute
  '/teach/marks': typeof TeachMarksRoute
  '/teach/syllabus': typeof TeachSyllabusRoute
  '/welcome/$token': typeof WelcomeTokenRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/teach/': typeof TeachIndexRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/platform/features': typeof AppPlatformFeaturesRoute
  '/app/platform/institutes': typeof AppPlatformInstitutesRoute
  '/app/platform/plans': typeof AppPlatformPlansRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/tests/$id': typeof AppTestsIdRoute
  '/app/platform/': typeof AppPlatformIndexRoute
  '/api/public/attendance/punch': typeof ApiPublicAttendancePunchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/apply'
    | '/for-institutes'
    | '/forgot-password'
    | '/guide'
    | '/pending'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/teach'
    | '/app/admissions'
    | '/app/attendance'
    | '/app/batches'
    | '/app/expenses'
    | '/app/faculty'
    | '/app/fees'
    | '/app/group'
    | '/app/messages'
    | '/app/platform'
    | '/app/reports'
    | '/app/salaries'
    | '/app/settings'
    | '/app/students'
    | '/app/syllabus'
    | '/app/tests'
    | '/app/timetable'
    | '/auth/callback'
    | '/join/$token'
    | '/login/$'
    | '/onboard/$token'
    | '/portal/attendance'
    | '/portal/fees'
    | '/portal/homework'
    | '/portal/progress'
    | '/portal/timetable'
    | '/teach/attendance'
    | '/teach/marks'
    | '/teach/syllabus'
    | '/welcome/$token'
    | '/app/'
    | '/login/'
    | '/portal/'
    | '/teach/'
    | '/app/batches/$id'
    | '/app/platform/features'
    | '/app/platform/institutes'
    | '/app/platform/plans'
    | '/app/students/$id'
    | '/app/tests/$id'
    | '/app/platform/'
    | '/api/public/attendance/punch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/for-institutes'
    | '/forgot-password'
    | '/guide'
    | '/pending'
    | '/pricing'
    | '/signup'
    | '/app/admissions'
    | '/app/attendance'
    | '/app/batches'
    | '/app/expenses'
    | '/app/faculty'
    | '/app/fees'
    | '/app/group'
    | '/app/messages'
    | '/app/reports'
    | '/app/salaries'
    | '/app/settings'
    | '/app/students'
    | '/app/syllabus'
    | '/app/tests'
    | '/app/timetable'
    | '/auth/callback'
    | '/join/$token'
    | '/login/$'
    | '/onboard/$token'
    | '/portal/attendance'
    | '/portal/fees'
    | '/portal/homework'
    | '/portal/progress'
    | '/portal/timetable'
    | '/teach/attendance'
    | '/teach/marks'
    | '/teach/syllabus'
    | '/welcome/$token'
    | '/app'
    | '/login'
    | '/portal'
    | '/teach'
    | '/app/batches/$id'
    | '/app/platform/features'
    | '/app/platform/institutes'
    | '/app/platform/plans'
    | '/app/students/$id'
    | '/app/tests/$id'
    | '/app/platform'
    | '/api/public/attendance/punch'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/apply'
    | '/for-institutes'
    | '/forgot-password'
    | '/guide'
    | '/pending'
    | '/portal'
    | '/pricing'
    | '/signup'
    | '/teach'
    | '/app/admissions'
    | '/app/attendance'
    | '/app/batches'
    | '/app/expenses'
    | '/app/faculty'
    | '/app/fees'
    | '/app/group'
    | '/app/messages'
    | '/app/platform'
    | '/app/reports'
    | '/app/salaries'
    | '/app/settings'
    | '/app/students'
    | '/app/syllabus'
    | '/app/tests'
    | '/app/timetable'
    | '/auth/callback'
    | '/join/$token'
    | '/login/$'
    | '/onboard/$token'
    | '/portal/attendance'
    | '/portal/fees'
    | '/portal/homework'
    | '/portal/progress'
    | '/portal/timetable'
    | '/teach/attendance'
    | '/teach/marks'
    | '/teach/syllabus'
    | '/welcome/$token'
    | '/app/'
    | '/login/'
    | '/portal/'
    | '/teach/'
    | '/app/batches/$id'
    | '/app/platform/features'
    | '/app/platform/institutes'
    | '/app/platform/plans'
    | '/app/students/$id'
    | '/app/tests/$id'
    | '/app/platform/'
    | '/api/public/attendance/punch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  ForInstitutesRoute: typeof ForInstitutesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  PendingRoute: typeof PendingRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  TeachRoute: typeof TeachRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LoginSplatRoute: typeof LoginSplatRoute
  OnboardTokenRoute: typeof OnboardTokenRoute
  WelcomeTokenRoute: typeof WelcomeTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiPublicAttendancePunchRoute: typeof ApiPublicAttendancePunchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-institutes': {
      id: '/for-institutes'
      path: '/for-institutes'
      fullPath: '/for-institutes'
      preLoaderRoute: typeof ForInstitutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admissions': {
      id: '/app/admissions'
      path: '/admissions'
      fullPath: '/app/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches': {
      id: '/app/batches'
      path: '/batches'
      fullPath: '/app/batches'
      preLoaderRoute: typeof AppBatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faculty': {
      id: '/app/faculty'
      path: '/faculty'
      fullPath: '/app/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/group': {
      id: '/app/group'
      path: '/group'
      fullPath: '/app/group'
      preLoaderRoute: typeof AppGroupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/platform': {
      id: '/app/platform'
      path: '/platform'
      fullPath: '/app/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salaries': {
      id: '/app/salaries'
      path: '/salaries'
      fullPath: '/app/salaries'
      preLoaderRoute: typeof AppSalariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/syllabus': {
      id: '/app/syllabus'
      path: '/syllabus'
      fullPath: '/app/syllabus'
      preLoaderRoute: typeof AppSyllabusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests': {
      id: '/app/tests'
      path: '/tests'
      fullPath: '/app/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$token': {
      id: '/onboard/$token'
      path: '/onboard/$token'
      fullPath: '/onboard/$token'
      preLoaderRoute: typeof OnboardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/attendance': {
      id: '/portal/attendance'
      path: '/attendance'
      fullPath: '/portal/attendance'
      preLoaderRoute: typeof PortalAttendanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/fees': {
      id: '/portal/fees'
      path: '/fees'
      fullPath: '/portal/fees'
      preLoaderRoute: typeof PortalFeesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/homework': {
      id: '/portal/homework'
      path: '/homework'
      fullPath: '/portal/homework'
      preLoaderRoute: typeof PortalHomeworkRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/progress': {
      id: '/portal/progress'
      path: '/progress'
      fullPath: '/portal/progress'
      preLoaderRoute: typeof PortalProgressRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/timetable': {
      id: '/portal/timetable'
      path: '/timetable'
      fullPath: '/portal/timetable'
      preLoaderRoute: typeof PortalTimetableRouteImport
      parentRoute: typeof PortalRoute
    }
    '/teach/': {
      id: '/teach/'
      path: '/'
      fullPath: '/teach/'
      preLoaderRoute: typeof TeachIndexRouteImport
      parentRoute: typeof TeachRoute
    }
    '/teach/attendance': {
      id: '/teach/attendance'
      path: '/attendance'
      fullPath: '/teach/attendance'
      preLoaderRoute: typeof TeachAttendanceRouteImport
      parentRoute: typeof TeachRoute
    }
    '/teach/marks': {
      id: '/teach/marks'
      path: '/marks'
      fullPath: '/teach/marks'
      preLoaderRoute: typeof TeachMarksRouteImport
      parentRoute: typeof TeachRoute
    }
    '/teach/syllabus': {
      id: '/teach/syllabus'
      path: '/syllabus'
      fullPath: '/teach/syllabus'
      preLoaderRoute: typeof TeachSyllabusRouteImport
      parentRoute: typeof TeachRoute
    }
    '/welcome/$token': {
      id: '/welcome/$token'
      path: '/welcome/$token'
      fullPath: '/welcome/$token'
      preLoaderRoute: typeof WelcomeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/batches/$id': {
      id: '/app/batches/$id'
      path: '/$id'
      fullPath: '/app/batches/$id'
      preLoaderRoute: typeof AppBatchesIdRouteImport
      parentRoute: typeof AppBatchesRoute
    }
    '/app/platform/': {
      id: '/app/platform/'
      path: '/'
      fullPath: '/app/platform/'
      preLoaderRoute: typeof AppPlatformIndexRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/app/platform/features': {
      id: '/app/platform/features'
      path: '/features'
      fullPath: '/app/platform/features'
      preLoaderRoute: typeof AppPlatformFeaturesRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/app/platform/institutes': {
      id: '/app/platform/institutes'
      path: '/institutes'
      fullPath: '/app/platform/institutes'
      preLoaderRoute: typeof AppPlatformInstitutesRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/app/platform/plans': {
      id: '/app/platform/plans'
      path: '/plans'
      fullPath: '/app/platform/plans'
      preLoaderRoute: typeof AppPlatformPlansRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/app/students/$id': {
      id: '/app/students/$id'
      path: '/$id'
      fullPath: '/app/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
    '/app/tests/$id': {
      id: '/app/tests/$id'
      path: '/$id'
      fullPath: '/app/tests/$id'
      preLoaderRoute: typeof AppTestsIdRouteImport
      parentRoute: typeof AppTestsRoute
    }
    '/api/public/attendance/punch': {
      id: '/api/public/attendance/punch'
      path: '/api/public/attendance/punch'
      fullPath: '/api/public/attendance/punch'
      preLoaderRoute: typeof ApiPublicAttendancePunchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppBatchesRouteChildren {
  AppBatchesIdRoute: typeof AppBatchesIdRoute
}

const AppBatchesRouteChildren: AppBatchesRouteChildren = {
  AppBatchesIdRoute: AppBatchesIdRoute,
}

const AppBatchesRouteWithChildren = AppBatchesRoute._addFileChildren(
  AppBatchesRouteChildren,
)

interface AppPlatformRouteChildren {
  AppPlatformFeaturesRoute: typeof AppPlatformFeaturesRoute
  AppPlatformInstitutesRoute: typeof AppPlatformInstitutesRoute
  AppPlatformPlansRoute: typeof AppPlatformPlansRoute
  AppPlatformIndexRoute: typeof AppPlatformIndexRoute
}

const AppPlatformRouteChildren: AppPlatformRouteChildren = {
  AppPlatformFeaturesRoute: AppPlatformFeaturesRoute,
  AppPlatformInstitutesRoute: AppPlatformInstitutesRoute,
  AppPlatformPlansRoute: AppPlatformPlansRoute,
  AppPlatformIndexRoute: AppPlatformIndexRoute,
}

const AppPlatformRouteWithChildren = AppPlatformRoute._addFileChildren(
  AppPlatformRouteChildren,
)

interface AppStudentsRouteChildren {
  AppStudentsIdRoute: typeof AppStudentsIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsIdRoute: AppStudentsIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppTestsRouteChildren {
  AppTestsIdRoute: typeof AppTestsIdRoute
}

const AppTestsRouteChildren: AppTestsRouteChildren = {
  AppTestsIdRoute: AppTestsIdRoute,
}

const AppTestsRouteWithChildren = AppTestsRoute._addFileChildren(
  AppTestsRouteChildren,
)

interface AppRouteChildren {
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBatchesRoute: typeof AppBatchesRouteWithChildren
  AppExpensesRoute: typeof AppExpensesRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppFeesRoute: typeof AppFeesRoute
  AppGroupRoute: typeof AppGroupRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPlatformRoute: typeof AppPlatformRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSalariesRoute: typeof AppSalariesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppSyllabusRoute: typeof AppSyllabusRoute
  AppTestsRoute: typeof AppTestsRouteWithChildren
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBatchesRoute: AppBatchesRouteWithChildren,
  AppExpensesRoute: AppExpensesRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppFeesRoute: AppFeesRoute,
  AppGroupRoute: AppGroupRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPlatformRoute: AppPlatformRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSalariesRoute: AppSalariesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppSyllabusRoute: AppSyllabusRoute,
  AppTestsRoute: AppTestsRouteWithChildren,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAttendanceRoute: typeof PortalAttendanceRoute
  PortalFeesRoute: typeof PortalFeesRoute
  PortalHomeworkRoute: typeof PortalHomeworkRoute
  PortalProgressRoute: typeof PortalProgressRoute
  PortalTimetableRoute: typeof PortalTimetableRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAttendanceRoute: PortalAttendanceRoute,
  PortalFeesRoute: PortalFeesRoute,
  PortalHomeworkRoute: PortalHomeworkRoute,
  PortalProgressRoute: PortalProgressRoute,
  PortalTimetableRoute: PortalTimetableRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface TeachRouteChildren {
  TeachAttendanceRoute: typeof TeachAttendanceRoute
  TeachMarksRoute: typeof TeachMarksRoute
  TeachSyllabusRoute: typeof TeachSyllabusRoute
  TeachIndexRoute: typeof TeachIndexRoute
}

const TeachRouteChildren: TeachRouteChildren = {
  TeachAttendanceRoute: TeachAttendanceRoute,
  TeachMarksRoute: TeachMarksRoute,
  TeachSyllabusRoute: TeachSyllabusRoute,
  TeachIndexRoute: TeachIndexRoute,
}

const TeachRouteWithChildren = TeachRoute._addFileChildren(TeachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApplyRoute: ApplyRoute,
  ForInstitutesRoute: ForInstitutesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  PendingRoute: PendingRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  TeachRoute: TeachRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinTokenRoute: JoinTokenRoute,
  LoginSplatRoute: LoginSplatRoute,
  OnboardTokenRoute: OnboardTokenRoute,
  WelcomeTokenRoute: WelcomeTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiPublicAttendancePunchRoute: ApiPublicAttendancePunchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
